name: Publish PowerShell Module
on:
  push:
   tags:
    - '[0-9]+.[0-9]+.[0-9]+'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
      # API key generated in PSGallery
        env:
          NUGET_KEY: ${{ secrets.NUGGET_KEY }}
        shell: pwsh
        run: |
          Publish-Module -path ./terraform-tools -NuGetApiKey $env:NUGET_KEY -Verbose      